### PR TITLE
Line continuations for indentation

### PR DESCRIPTION
**Pull request by acrmp**
Hi Steve,

This is an implementation (really for feedback at this stage) of line-continuation support, related issues are #102 and #92. 

I expect the implementation may be controversial - I've used Ripper's s-expression support rather than trying to determine expression start and end from the lexer tokens. It's also using Nokogiri (as I do elsewhere in foodcritic) to query the AST - that's unconventional and adds a significant new dependency.

Would really appreciate your feedback. 

Thanks,

Andrew.

### CODE REVIEW

**Comment by turboladen** [comment]
Interesting approach--I'm intrigued.  I haven't been super pleased with the indentation checking solution that I'd implemented, so any help/fresh ideas towards better sorting that out are certainly welcome.  Thanks for shooting it over; I'll dig into it this coming weekend.

**Comment by jaymzh** [comment]
@acrmp This isn't passing CI builds....
@turboladen any concerns with this since your last comment?

**Comment by turboladen** [comment]
@acrmp @jaymzh I think everything looks fine to me.  I'm a fan of, although not super familiar with, nokogiri, so I can't be 100% critical on that code.  Once the tests pass, I'll merge.

**Comment by jaymzh** [comment]
My understanding is that these aren't passing because of some other change - @acrmp  said they should be passing... :/

**Comment by turboladen** [comment]
Ah, yeah that could be.  I should’ve checked the actual errors before commenting…

**Pull request closed without merging**
